"""Tests for the model-validation layer (fce.validate).

These check that the *validators* have both correctness and diagnostic power:
a well-specified model passes, and a deliberately misspecified one is flagged.
"""

from __future__ import annotations

import numpy as np

from fce.drivers.hmm import HMMPosterior
from fce.drivers.history import (
    _TRUE_INIT,
    _TRUE_LOCS,
    _TRUE_SCALES,
    _TRUE_TRANS,
    simulate_true_hmm,
)
from fce.term_structure import synthetic_treasury_curve
from fce.validate import (
    hmm_one_step_var,
    kupiec_pof,
    posterior_predictive_check,
    reprice_curve,
    var_backtest,
)


def _point_mass_posterior(locs, scales, trans, init, *, d: int = 40) -> HMMPosterior:
    """A 'posterior' with all mass at fixed params — for fast, exact validation."""
    locs, scales = np.asarray(locs, float), np.asarray(scales, float)
    trans, init = np.asarray(trans, float), np.asarray(init, float)
    return HMMPosterior(
        probs_init=np.tile(init, (d, 1)),
        probs_trans=np.tile(trans, (d, 1, 1)),
        locs=np.tile(locs, (d, 1)),
        scales=np.tile(scales, (d, 1)),
        n_states=len(locs),
    )


# --------------------------------------------------------------------------- #
# 1. Curve repricing round-trip
# --------------------------------------------------------------------------- #
def test_curve_reprices_its_inputs():
    tenors, par = synthetic_treasury_curve()
    res = reprice_curve(tenors, par)
    # A correctly bootstrapped curve reprices deposits and swaps to ~machine zero.
    assert res.max_abs_bp < 0.5
    assert len(res.residuals_bp) == len(tenors)
    assert set(res.kinds) == {"deposit", "swap"}


# --------------------------------------------------------------------------- #
# 2. HMM posterior predictive checks
# --------------------------------------------------------------------------- #
def test_ppc_does_not_flag_the_true_model():
    returns, _ = simulate_true_hmm(420, seed=1)
    post = _point_mass_posterior(_TRUE_LOCS, _TRUE_SCALES, _TRUE_TRANS, _TRUE_INIT)
    ppc = posterior_predictive_check(returns, post, n_rep=300, seed=0)
    # Data generated by this very model: no statistic should be in an extreme tail.
    assert ppc.worst_pvalue() > 0.02


def test_ppc_flags_single_regime_misspecification():
    returns, _ = simulate_true_hmm(420, seed=1)
    # A single-volatility (GBM-like) model can't produce the crisis tail/clustering.
    mu, sd = returns.mean(), returns.std()
    bad = _point_mass_posterior([mu, mu], [sd, sd],
                                [[0.5, 0.5], [0.5, 0.5]], [0.5, 0.5])
    ppc = posterior_predictive_check(returns, bad, n_rep=300, seed=0)
    # Fat tails and volatility clustering are exactly what it misses.
    assert ppc.p_values["kurtosis"] < 0.05
    assert ppc.p_values["acf1_sq"] < 0.05


# --------------------------------------------------------------------------- #
# 3. VaR exceedance / Kupiec–Christoffersen backtest
# --------------------------------------------------------------------------- #
def test_hmm_var_backtest_is_well_calibrated():
    returns, _ = simulate_true_hmm(420, seed=1)
    post = _point_mass_posterior(_TRUE_LOCS, _TRUE_SCALES, _TRUE_TRANS, _TRUE_INIT)
    var = hmm_one_step_var(returns, post, alpha=0.95)
    assert np.all(var > 0)
    bt = var_backtest(returns, var, alpha=0.95)
    # ~5% exceptions, and neither coverage test rejects.
    assert abs(bt.observed_rate - 0.05) < 0.03
    assert bt.kupiec_ok
    assert bt.christoffersen_p > 0.05


def test_var_backtest_rejects_a_too_tight_var():
    rng = np.random.default_rng(0)
    returns = rng.normal(0.0, 0.05, size=500)
    # A VaR far too small is breached far more than 5% of the time.
    bt = var_backtest(returns, np.full(500, 0.01), alpha=0.95)
    assert bt.observed_rate > 0.20
    assert not bt.kupiec_ok                    # Kupiec rejects


def test_kupiec_pof_direction():
    # 10% exceptions at a 95% level (expect 5%) should reject; 5% should not.
    _, p_bad = kupiec_pof(1000, 100, 0.05)
    _, p_ok = kupiec_pof(1000, 50, 0.05)
    assert p_bad < 0.05
    assert p_ok > 0.05
